#!/usr/bin/python3
# -*- coding: utf-8 -*-
import glob
import re
import sys

sys.path.insert(1, glob.glob("/usr/local/aion-*/aion_core/shell")[0])

from shell import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r"(-script\.pyw?|\.exe)?$", "", sys.argv[0])
    sys.exit(main())
